Squashed commit of the following:
commit d2113befb67d79a667b6dedde8647bf85a7d8d30
Author: hanli17 <hanli17@iflytek.com>
Date:   Fri Aug 14 16:36:23 2026 +0800

    fix: 修复Nacos 缺少依赖

commit 0775251743a4e05fbd97d7ef1aa4c108d55b5dbd
Author: hanli17 <hanli17@iflytek.com>
Date:   Fri Aug 14 15:56:25 2026 +0800

    fix: shade 补充 jackson-datatype-jsr310，修复 Dubbo JsonUtils 加载 JavaTimeModule 失败

    Dubbo3 应用级发现获取远程元数据时, JsonUtils 经 ServiceLoader 加载 jackson 扩展, 引用的 JavaTimeModule 缺失导致 NoClassDefFoundError(GUI 模式必现)。

commit 27030fd1abb24e59c2063772606f7f4b788449ed
Author: hanli17 <hanli17@iflytek.com>
Date:   Fri Aug 14 15:38:41 2026 +0800

    feat: 升级 Dubbo 3.3.6 支持 Nacos 应用级发现

    - dubbo.version 2.7.23 -> 3.3.6
    - 删除未使用的自定义 dubbo 序列化类(serialize/dubbo)
    - ReferenceConfigCache -> SimpleReferenceCache, ApplicationModel API 适配
    - 新增 serviceProvider(provided-by) 字段, 支持 Dubbo3 应用级发现
    - RegistryConfig username/password 以 URL 参数注入(Nacos 鉴权)
    - shade 补充 fastjson2/micrometer
    - 新增 Nacos 命名空间/accessKey/secretKey 配置(早前提交)
    - 修复服务组 setGroup 与 gson 参数传 JSON 字符串(早前提交)

    验证: Nacos 发现与直连均成功调用 CaseStudyService.reportStudy(返回业务异常案例不存在或已删除)

commit e017d80d325320a1d9a594d5987d575914d7620a
Author: hanli17 <hanli17@iflytek.com>
Date:   Fri Aug 14 14:19:29 2026 +0800

    checkpoint: Nacos配置支持+服务组/gson参数修复 (Dubbo2.7可直连验证)